# Generated by Django 5.2.10 on 2026-01-14 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=255)),
                ('new_content', models.TextField()),
                ('reason', models.TextField(blank=True, help_text='Reason for the edit')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='home.document')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_edit_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='document_ed_documen_a27889_idx'), models.Index(fields=['requested_by'], name='document_ed_request_6e9188_idx'), models.Index(fields=['status'], name='document_ed_status_429578_idx'), models.Index(fields=['created_at'], name='document_ed_created_7575dc_idx')],
            },
        ),
    ]
